service: tm-stravabot

package:
  individually: true

plugins:
  - serverless-bundle # Package our functions with Webpack
  - serverless-offline
  - serverless-dotenv-plugin # Load .env as environment variables

provider:
  name: aws
  runtime: nodejs12.x
  stage: prod
  region: eu-west-2
  profile: stravabot

functions:
  leaderboard:
    handler: src/leaderboard.leaderboard
    events:
      - http:
          path: leaderboard
          method: post
  authLink:
    handler: src/auth.auth
    events:
      - http:
          path: auth
          method: post
  auth:
    handler: src/auth.auth
    events:
      - http:
          path: auth
          method: get
  authCallback:
    handler: src/auth.authCallback
    events:
      - http:
          path: authCallback
          method: get
