# NOTE: update this with your service name
service: totallyrunning-slackbot

# Create an optimized package for our functions
package:
  individually: true

plugins:
  - serverless-bundle # Package our functions with Webpack
  - serverless-offline
  - serverless-dotenv-plugin # Load .env as environment variables

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: us-east-1

functions:
  slack:
    handler: src/index.slack
    events:
      - http:
          path: slack
          method: post
  auth:
    handler: src/index.auth
    events:
      - http:
          path: auth
          method: get
  authCallback:
    handler: src/index.authCallback
    events:
      - http:
          path: authCallback
          method: get
